language: node_js
node_js:
  - lts/*
script:
  - npm audit
  - npm run build
  - cp CNAME ./build
branches:
  except:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: ./build
  target_branch: master
  on:
    branch: develop
env:
  global:
    secure: pklLMqJm5IRXslzsaZI+VyKdPWXmPkaPtqd7g1VFW2Xo3q2bSU64cSob5cnV13pAZfA6TUgdfFGpaJjsNC/joZdQtOVdKDCz7AoCdoBsDt9AXJLeZ0haIyvpuAS4zjYIokl3tSIiJz4YP5Im3JAyuNwD1gKWXQyDvrWX7xz5yeBqaTR0J1jaqy8iFHq9UdXu1ehb46r9vTrwBJk832VLxL7t3y7LUQk9C9COPKv0HEn1EUr7MkbMQNWeh9uHl/FkkFRpgiFjP6nb9uBqcsbdTCk1xxl/bGPZfM+BvEl4Cku3OI0Q9kmDMHpXCmxZa8qDVnj0xaf4ectQwQB3LtLSv2gFHiH0ugEYv8j0o7k2V4uPzuKftCPjIlQmPJ9f4bDAD7HvtwFApPDVGPuXBQGeSyGWj+mhc7gd4YsGLsxvRvkk3kBOw5AxLhieUBhOwwz+gFyilCiyowccxCeLNWxIMCIIdMREmvACuLLIxfnHo9YbKEM670gvuc4JbtOeR387aleA9L+nzu0UMU2vnKStWK56xaSBN69/fQocqmvMEVCY8hY35jVyfvVnDPlr6D7xvbafLFzNsmARntqUgsw9qrEpX0PAx6tPX030pQeKZG85B7N9U3fe3AmklM2F4Nxl7peHQXNP3JRl5PD7pBeCtaFyIwPhf5h1er5kq9i1RFE=
